### ISSUE TITLE
metadata for Landsat collection not complete - requires updating

### ISSUE THREAD

**Issue by simonaoliver** [opendatacube/eo-datasets#21]
**PQ:**
Relevant snippets defining product:
pq_metadata.yml should be ga-metadata.yml for consistency
software version in pq metadata not populated and lineage from L1T and NBAR need to be included

``` yaml
software_repository: https://github.com/GeoscienceAustralia/ga-neo-landsat-processor.git
  software_version: _!!python/unicode_ '4.1+3.g73458ae.dirty'
```

**NBAR/T:**
Relevant snippets defining product:

``` yaml
            eodatasets:
                repo_url: https://github.com/GeoscienceAustralia/eo-datasets.git
                version: 0.2.2+13.gc397b5b
            _nbar: 4.1+dirty_

            lineage:
                algorithm:
                    name: LPGS
                    version: 12.7.0
```

**Level1 lineage looks like this which is good!!! - addressing this issue will aim to maintain consistency in NBAR/T and PQ products:NBAR and PQ should style and build from this example**

``` yaml
lineage:
    algorithm:
        name: LPGS
        version: 12.7.0
            eodatasets:
                repo_url: https://github.com/GeoscienceAustralia/eo-datasets.git
                version: '0.4'
            galpgs:
                repo_url: https://github.com/GeoscienceAustralia/galpgs.git
                version: 1.1.1
            gqa:
                repo_url: https://github.com/GeoscienceAustralia/gqa.git
                version: '0.6'
            pinkmatter: 4.1.4084
```

**Comment by simonaoliver** [comment]
`````` yaml
PQ example
algorithm_information:
  pq_doi: http://dx.doi.org/10.1109/IGARSS.2013.6723746
  software_repository: https://github.com/GeoscienceAustralia/ga-neo-landsat-processor.git
  software_version: !!python/unicode '4.1+3.g73458ae.dirty'
ancillary:
  land_sea_mask:
    accessed: 2016-05-23 05:24:41
    change: 2015-12-23 02:33:15
    data_file: /g/data/v10/eoancillarydata/Land_Sea_Rasters/WORLDzone50.tif
    data_source: Rasterised Land/Sea Mask
    modified: 2013-11-04 01:30:25
    user: Joshua Sixsmith
source_data:
  source_l1t: /g/data/v10/reprocess/ls5/level1/2011/01/LS5_TM_OTH_P51_GALPGS01-002_114_075_20110116
  source_nbar: /g/data/v10/reprocess/ls5/nbar/2011/01/output/nbar/LS5_TM_NBAR_P54_GANBAR01-002_114_075_20110116
system_information:
  node: 'Linux r349 2.6.32-573.22.1.el6.x86_64 #1 SMP Wed Mar 23 03:35:39 UTC 2016
    x86_64 x86_64 x86_64 GNU/Linux

    '
  time_processed: 2016-05-23 05:28:59.888722
tests_run:
  band_1_saturated: true
  band_2_saturated: true
  band_3_saturated: true
  band_4_saturated: true
  band_5_saturated: true
  band_6_saturated: true
  band_7_saturated: true
  cloud_acca: true
  cloud_fmask: true
  cloud_shadow_acca: true
  cloud_shadow_fmask: true
  contiguity: true
  land_obs: true```


``````

**Comment by simonaoliver** [comment]
**NBAR example:**

``` yaml
id: d990ca1e-209a-11e6-9d9b-a0000100fe80
ga_label: LS5_TM_NBAR_P54_GANBAR01-002_114_075_20110116
ga_level: P54
product_type: nbar
product_doi: http://dx.doi.org/10.4225/25/5487CC0D4F40B
creation_dt: 2016-05-23 04:00:12
size_bytes: 273068251
checksum_path: package.sha1
platform:
    code: LANDSAT_5
instrument:
    name: TM
    operation_mode: BUMPER
format:
    name: GeoTIFF
acquisition:
    groundstation:
        code: ASA
        label: Alice Springs
        eods_domain_code: '002'
extent:
    coord:
        ul:
            lat: -20.72316
            lon: 114.930237
        ur:
            lat: -20.735474
            lon: 117.217916
        ll:
            lat: -22.607272
            lon: 114.903166
        lr:
            lat: -22.62082
            lon: 117.220769
    from_dt: 2011-01-16 02:04:44
    center_dt: 2011-01-16 02:04:57.817019
    to_dt: 2011-01-16 02:05:11
grid_spatial:
    projection:
        geo_ref_points:
            ul:
                x: 284462.5
                y: 7707112.5
            ur:
                x: 522687.5
                y: 7707112.5
            ll:
                x: 284462.5
                y: 7498437.5
            lr:
                x: 522687.5
                y: 7498437.5
        datum: GDA94
        ellipsoid: GRS80
        map_projection: UTM
        orientation: NORTH_UP
        resampling_option: CUBIC_CONVOLUTION
        zone: -50
browse:
    full:
        path: browse.fr.jpg
        file_type: image/jpg
        cell_size: 25.0
        shape:
            x: 9530
            y: 8348
        red_band: '7'
        green_band: '4'
        blue_band: '1'
    medium:
        path: browse.jpg
        file_type: image/jpg
        cell_size: 232.666015625
        shape:
            x: 1024
            y: 897
        red_band: '7'
        green_band: '4'
        blue_band: '1'
image:
    satellite_ref_point_start:
        x: 114
        y: 75
    bands:
        '1':
            path: product/LS5_TM_NBAR_P54_GANBAR01-002_114_075_20110116_B1.tif
            type: reflective
            label: Visible Blue
            number: '1'
            cell_size: 25.0
        '2':
            path: product/LS5_TM_NBAR_P54_GANBAR01-002_114_075_20110116_B2.tif
            type: reflective
            label: Visible Green
            number: '2'
            cell_size: 25.0
        '3':
            path: product/LS5_TM_NBAR_P54_GANBAR01-002_114_075_20110116_B3.tif
            type: reflective
            label: Visible Red
            number: '3'
            cell_size: 25.0
        '4':
            path: product/LS5_TM_NBAR_P54_GANBAR01-002_114_075_20110116_B4.tif
            type: reflective
            label: Near Infrared
            number: '4'
            cell_size: 25.0
        '5':
            path: product/LS5_TM_NBAR_P54_GANBAR01-002_114_075_20110116_B5.tif
            type: reflective
            label: Middle Infrared 1
            number: '5'
            cell_size: 25.0
        '7':
            path: product/LS5_TM_NBAR_P54_GANBAR01-002_114_075_20110116_B7.tif
            type: reflective
            label: Middle Infrared 2
            number: '7'
            cell_size: 25.0
lineage:
    algorithm:
        name: brdf
        version: '2.0'
        doi: http://dx.doi.org/10.1109/JSTARS.2010.2042281
        parameters:
            aerosol: 0.057921
            band_1_brdf_geo: 0.005242038962629312
            band_1_brdf_iso: 0.04904892424169821
            band_1_brdf_vol: 0.021272812944239463
            band_2_brdf_geo: 0.014667021783471543
            band_2_brdf_iso: 0.08289289213193214
            band_2_brdf_vol: 0.03556388622699994
            band_3_brdf_geo: 0.026722573028474878
            band_3_brdf_iso: 0.13395938349561884
            band_3_brdf_vol: 0.048169040475700496
            band_4_brdf_geo: 0.02745571203930076
            band_4_brdf_iso: 0.20139412669444348
            band_4_brdf_vol: 0.11398417754209565
            band_5_brdf_geo: 0.04293091174200189
            band_5_brdf_iso: 0.2784452300797667
            band_5_brdf_vol: 0.1205125600394545
            band_7_brdf_geo: 0.04074984741570387
            band_7_brdf_iso: 0.23319493313060144
            band_7_brdf_vol: 0.08597556509727919
            elevation: 0.0
            ozone: 0.25799999
            solar_distance: 0.98371
            water_vapour: 5.230000305175782
    machine:
        hostname: r1226
        runtime_id: 968925dc-2094-11e6-9d9b-a0000100fe80
        software_versions:
            eodatasets:
                repo_url: https://github.com/GeoscienceAustralia/eo-datasets.git
                version: 0.2.2+13.gc397b5b
            nbar: 4.1+dirty
        uname: 'Linux r1226 2.6.32-573.22.1.el6.x86_64 #1 SMP Wed Mar 23 03:35:39
            UTC 2016 x86_64'
    ancillary:
        aerosol:
            type: aerosol
            name: aot_mean_Jan_All_Aerosols.cmp
            uri: /g/data/v10/eoancillarydata/aerosol/AATSR/2.0/aot_mean_Jan_All_Aerosols.cmp
            access_dt: 2016-05-23 03:52:06
            modification_dt: 2012-07-12 01:19:44
            file_owner: Roger Edberg
        band_1_brdf_geo:
            type: band_1_brdf_geo
            name: MCD43A1.2011.009.aust.005.b09.500m_0459_0479nm_brdf_par_fgeo.hdf.gz
            uri: /g/data/u39/public/data/modis/lpdaac-mosaics-cmar/v1-hdf4/aust/MCD43A1.005/2011.01.09/MCD43A1.2011.009.aust.005.b09.500m_0459_0479nm_brdf_par_fgeo.hdf.gz
            access_dt: 2016-05-23 03:52:05
            modification_dt: 2011-02-09 13:29:50
            file_owner: Matt Paget
        band_1_brdf_iso:
            type: band_1_brdf_iso
            name: MCD43A1.2011.009.aust.005.b07.500m_0459_0479nm_brdf_par_fiso.hdf.gz
            uri: /g/data/u39/public/data/modis/lpdaac-mosaics-cmar/v1-hdf4/aust/MCD43A1.005/2011.01.09/MCD43A1.2011.009.aust.005.b07.500m_0459_0479nm_brdf_par_fiso.hdf.gz
            access_dt: 2016-05-23 03:52:08
            modification_dt: 2011-02-09 13:29:42
            file_owner: Matt Paget
        band_1_brdf_vol:
            type: band_1_brdf_vol
            name: MCD43A1.2011.009.aust.005.b08.500m_0459_0479nm_brdf_par_fvol.hdf.gz
            uri: /g/data/u39/public/data/modis/lpdaac-mosaics-cmar/v1-hdf4/aust/MCD43A1.005/2011.01.09/MCD43A1.2011.009.aust.005.b08.500m_0459_0479nm_brdf_par_fvol.hdf.gz
            access_dt: 2016-05-23 03:52:11
            modification_dt: 2011-02-09 13:29:46
            file_owner: Matt Paget
        band_2_brdf_geo:
            type: band_2_brdf_geo
            name: MCD43A1.2011.009.aust.005.b12.500m_0545_0565nm_brdf_par_fgeo.hdf.gz
            uri: /g/data/u39/public/data/modis/lpdaac-mosaics-cmar/v1-hdf4/aust/MCD43A1.005/2011.01.09/MCD43A1.2011.009.aust.005.b12.500m_0545_0565nm_brdf_par_fgeo.hdf.gz
            access_dt: 2016-05-23 03:52:14
            modification_dt: 2011-02-09 13:30:09
            file_owner: Matt Paget
        band_2_brdf_iso:
            type: band_2_brdf_iso
            name: MCD43A1.2011.009.aust.005.b10.500m_0545_0565nm_brdf_par_fiso.hdf.gz
            uri: /g/data/u39/public/data/modis/lpdaac-mosaics-cmar/v1-hdf4/aust/MCD43A1.005/2011.01.09/MCD43A1.2011.009.aust.005.b10.500m_0545_0565nm_brdf_par_fiso.hdf.gz
            access_dt: 2016-05-23 03:52:18
            modification_dt: 2011-02-09 13:29:55
            file_owner: Matt Paget
        band_2_brdf_vol:
            type: band_2_brdf_vol
            name: MCD43A1.2011.009.aust.005.b11.500m_0545_0565nm_brdf_par_fvol.hdf.gz
            uri: /g/data/u39/public/data/modis/lpdaac-mosaics-cmar/v1-hdf4/aust/MCD43A1.005/2011.01.09/MCD43A1.2011.009.aust.005.b11.500m_0545_0565nm_brdf_par_fvol.hdf.gz
            access_dt: 2016-05-23 03:52:21
            modification_dt: 2011-02-09 13:30:04
            file_owner: Matt Paget
        band_3_brdf_geo:
            type: band_3_brdf_geo
            name: MCD43A1.2011.009.aust.005.b03.500m_0620_0670nm_brdf_par_fgeo.hdf.gz
            uri: /g/data/u39/public/data/modis/lpdaac-mosaics-cmar/v1-hdf4/aust/MCD43A1.005/2011.01.09/MCD43A1.2011.009.aust.005.b03.500m_0620_0670nm_brdf_par_fgeo.hdf.gz
            access_dt: 2016-05-23 03:52:25
            modification_dt: 2011-02-09 13:29:09
            file_owner: Matt Paget
        band_3_brdf_iso:
            type: band_3_brdf_iso
            name: MCD43A1.2011.009.aust.005.b01.500m_0620_0670nm_brdf_par_fiso.hdf.gz
            uri: /g/data/u39/public/data/modis/lpdaac-mosaics-cmar/v1-hdf4/aust/MCD43A1.005/2011.01.09/MCD43A1.2011.009.aust.005.b01.500m_0620_0670nm_brdf_par_fiso.hdf.gz
            access_dt: 2016-05-23 03:52:28
            modification_dt: 2011-02-09 13:28:55
            file_owner: Matt Paget
        band_3_brdf_vol:
            type: band_3_brdf_vol
            name: MCD43A1.2011.009.aust.005.b02.500m_0620_0670nm_brdf_par_fvol.hdf.gz
            uri: /g/data/u39/public/data/modis/lpdaac-mosaics-cmar/v1-hdf4/aust/MCD43A1.005/2011.01.09/MCD43A1.2011.009.aust.005.b02.500m_0620_0670nm_brdf_par_fvol.hdf.gz
            access_dt: 2016-05-23 03:52:32
            modification_dt: 2011-02-09 13:29:01
            file_owner: Matt Paget
        band_4_brdf_geo:
            type: band_4_brdf_geo
            name: MCD43A1.2011.009.aust.005.b06.500m_0841_0876nm_brdf_par_fgeo.hdf.gz
            uri: /g/data/u39/public/data/modis/lpdaac-mosaics-cmar/v1-hdf4/aust/MCD43A1.005/2011.01.09/MCD43A1.2011.009.aust.005.b06.500m_0841_0876nm_brdf_par_fgeo.hdf.gz
            access_dt: 2016-05-23 03:52:35
            modification_dt: 2011-02-09 13:29:34
            file_owner: Matt Paget
        band_4_brdf_iso:
            type: band_4_brdf_iso
            name: MCD43A1.2011.009.aust.005.b04.500m_0841_0876nm_brdf_par_fiso.hdf.gz
            uri: /g/data/u39/public/data/modis/lpdaac-mosaics-cmar/v1-hdf4/aust/MCD43A1.005/2011.01.09/MCD43A1.2011.009.aust.005.b04.500m_0841_0876nm_brdf_par_fiso.hdf.gz
            access_dt: 2016-05-23 03:52:39
            modification_dt: 2011-02-09 13:29:18
            file_owner: Matt Paget
        band_4_brdf_vol:
            type: band_4_brdf_vol
            name: MCD43A1.2011.009.aust.005.b05.500m_0841_0876nm_brdf_par_fvol.hdf.gz
            uri: /g/data/u39/public/data/modis/lpdaac-mosaics-cmar/v1-hdf4/aust/MCD43A1.005/2011.01.09/MCD43A1.2011.009.aust.005.b05.500m_0841_0876nm_brdf_par_fvol.hdf.gz
            access_dt: 2016-05-23 03:52:42
            modification_dt: 2011-02-09 13:29:27
            file_owner: Matt Paget
        band_5_brdf_geo:
            type: band_5_brdf_geo
            name: MCD43A1.2011.009.aust.005.b18.500m_1628_1652nm_brdf_par_fgeo.hdf.gz
            uri: /g/data/u39/public/data/modis/lpdaac-mosaics-cmar/v1-hdf4/aust/MCD43A1.005/2011.01.09/MCD43A1.2011.009.aust.005.b18.500m_1628_1652nm_brdf_par_fgeo.hdf.gz
            access_dt: 2016-05-23 03:52:46
            modification_dt: 2011-02-09 13:31:09
            file_owner: Matt Paget
        band_5_brdf_iso:
            type: band_5_brdf_iso
            name: MCD43A1.2011.009.aust.005.b16.500m_1628_1652nm_brdf_par_fiso.hdf.gz
            uri: /g/data/u39/public/data/modis/lpdaac-mosaics-cmar/v1-hdf4/aust/MCD43A1.005/2011.01.09/MCD43A1.2011.009.aust.005.b16.500m_1628_1652nm_brdf_par_fiso.hdf.gz
            access_dt: 2016-05-23 03:52:50
            modification_dt: 2011-02-09 13:30:45
            file_owner: Matt Paget
        band_5_brdf_vol:
            type: band_5_brdf_vol
            name: MCD43A1.2011.009.aust.005.b17.500m_1628_1652nm_brdf_par_fvol.hdf.gz
            uri: /g/data/u39/public/data/modis/lpdaac-mosaics-cmar/v1-hdf4/aust/MCD43A1.005/2011.01.09/MCD43A1.2011.009.aust.005.b17.500m_1628_1652nm_brdf_par_fvol.hdf.gz
            access_dt: 2016-05-23 03:52:53
            modification_dt: 2011-02-09 13:30:59
            file_owner: Matt Paget
        band_7_brdf_geo:
            type: band_7_brdf_geo
            name: MCD43A1.2011.009.aust.005.b21.500m_2105_2155nm_brdf_par_fgeo.hdf.gz
            uri: /g/data/u39/public/data/modis/lpdaac-mosaics-cmar/v1-hdf4/aust/MCD43A1.005/2011.01.09/MCD43A1.2011.009.aust.005.b21.500m_2105_2155nm_brdf_par_fgeo.hdf.gz
            access_dt: 2016-05-23 03:52:58
            modification_dt: 2011-02-09 13:31:28
            file_owner: Matt Paget
        band_7_brdf_iso:
            type: band_7_brdf_iso
            name: MCD43A1.2011.009.aust.005.b19.500m_2105_2155nm_brdf_par_fiso.hdf.gz
            uri: /g/data/u39/public/data/modis/lpdaac-mosaics-cmar/v1-hdf4/aust/MCD43A1.005/2011.01.09/MCD43A1.2011.009.aust.005.b19.500m_2105_2155nm_brdf_par_fiso.hdf.gz
            access_dt: 2016-05-23 03:53:01
            modification_dt: 2011-02-09 13:31:18
            file_owner: Matt Paget
        band_7_brdf_vol:
            type: band_7_brdf_vol
            name: MCD43A1.2011.009.aust.005.b20.500m_2105_2155nm_brdf_par_fvol.hdf.gz
            uri: /g/data/u39/public/data/modis/lpdaac-mosaics-cmar/v1-hdf4/aust/MCD43A1.005/2011.01.09/MCD43A1.2011.009.aust.005.b20.500m_2105_2155nm_brdf_par_fvol.hdf.gz
            access_dt: 2016-05-23 03:53:05
            modification_dt: 2011-02-09 13:31:23
            file_owner: Matt Paget
        elevation:
            type: elevation
            name: DEM_one_deg.tif
            uri: /g/data/v10/eoancillarydata/elevation/world_1deg/DEM_one_deg.tif
            access_dt: 2016-05-23 03:52:06
            modification_dt: 2010-02-23 21:59:29
            file_owner: Roger Edberg
        ozone:
            type: ozone
            name: jan.tif
            uri: /g/data/v10/eoancillarydata/lookup_tables/ozone/jan.tif
            access_dt: 2016-05-23 03:52:03
            modification_dt: 2010-02-23 22:00:21
            file_owner: Roger Edberg
        solar_distance:
            type: solar_distance
            name: EarthSun_distanceLUT.txt
            uri: /g/data/v10/eoancillarydata/lookup_tables/earthsun_distance/EarthSun_distanceLUT.txt
            access_dt: 2016-05-23 03:52:06
            modification_dt: 2012-05-21 02:04:01
            file_owner: Roger Edberg
        water_vapour:
            type: water_vapour
            name: pr_wtr.eatm.2011.tif
            uri: /g/data/v10/eoancillarydata/water_vapour/pr_wtr.eatm.2011.tif
            access_dt: 2016-05-23 03:52:04
            modification_dt: 2016-05-21 15:25:05
            file_owner: Landsat Processing
    source_datasets:
        ortho:
            id: 723e4fe2-1cd7-11e6-b44c-a0000100fe80
            ga_label: LS5_TM_OTH_P51_GALPGS01-002_114_075_20110116
            product_type: level1
            product_level: L1T
            creation_dt: 2016-05-18 08:42:44
            size_bytes: 172773914
            checksum_path: package.sha1
            platform:
                code: LANDSAT_5
            instrument:
                name: TM
                operation_mode: BUMPER
            format:
                name: GeoTIFF
            usgs:
                scene_id: LT51140752011016ASA00
            acquisition:
                groundstation:
                    code: ASA
                    label: Alice Springs
                    eods_domain_code: '002'
            extent:
                coord:
                    ul:
                        lat: -20.72316
                        lon: 114.930237
                    ur:
                        lat: -20.735474
                        lon: 117.217916
                    ll:
                        lat: -22.607272
                        lon: 114.903166
                    lr:
                        lat: -22.62082
                        lon: 117.220769
                from_dt: 2011-01-16 02:04:44
                center_dt: 2011-01-16 02:04:57.817019
                to_dt: 2011-01-16 02:05:11
            grid_spatial:
                projection:
                    geo_ref_points:
                        ul:
                            x: 284462.5
                            y: 7707112.5
                        ur:
                            x: 522687.5
                            y: 7707112.5
                        ll:
                            x: 284462.5
                            y: 7498437.5
                        lr:
                            x: 522687.5
                            y: 7498437.5
                    datum: GDA94
                    ellipsoid: GRS80
                    map_projection: UTM
                    orientation: NORTH_UP
                    resampling_option: CUBIC_CONVOLUTION
                    zone: -50
            gqa:
                cep90: 0.75
                colors:
                    blue: 192.0
                    green: 4033.0
                    red: 102.0
                    teal: 636.0
                    yellow: 97.0
                final_gcp_count: 5000
                ref_date: 2014-06-01
                ref_source: GQA_v2
                ref_source_path: /g/data/v10/eoancillarydata/GCP/GQA_v2/wrs2/114/075/LC81140752014152LGN00_B6.TIF
                residual:
                    abs:
                        x: 0.34
                        y: 0.47
                    abs_iterative_mean:
                        x: 0.24
                        y: 0.32
                    iterative_mean:
                        x: 0.01
                        y: 0.04
                    iterative_stddev:
                        x: 0.53
                        y: 0.73
                    mean:
                        x: 0.01
                        y: -0.0
                    stddev:
                        x: 1.59
                        y: 5.29
            browse:
                full:
                    path: browse.fr.jpg
                    file_type: image/jpg
                    cell_size: 25.0
                    shape:
                        x: 9530
                        y: 8348
                    red_band: '7'
                    green_band: '4'
                    blue_band: '1'
                medium:
                    path: browse.jpg
                    file_type: image/jpg
                    cell_size: 232.666015625
                    shape:
                        x: 1024
                        y: 897
                    red_band: '7'
                    green_band: '4'
                    blue_band: '1'
            image:
                satellite_ref_point_start:
                    x: 114
                    y: 75
                cloud_cover_percentage: 43.0
                sun_azimuth: 95.46312368
                sun_elevation: 57.39407158
                sun_earth_distance: 0.9836756
                ground_control_points_model: 47
                geometric_rmse_model: 5.421
                geometric_rmse_model_x: 3.982
                geometric_rmse_model_y: 3.678
                bands:
                    '1':
                        path: product/LT51140752011016ASA00_B1.TIF
                        type: reflective
                        label: Visible Blue
                        number: '1'
                        cell_size: 25.0
                    '2':
                        path: product/LT51140752011016ASA00_B2.TIF
                        type: reflective
                        label: Visible Green
                        number: '2'
                        cell_size: 25.0
                    '3':
                        path: product/LT51140752011016ASA00_B3.TIF
                        type: reflective
                        label: Visible Red
                        number: '3'
                        cell_size: 25.0
                    '4':
                        path: product/LT51140752011016ASA00_B4.TIF
                        type: reflective
                        label: Near Infrared
                        number: '4'
                        cell_size: 25.0
                    '5':
                        path: product/LT51140752011016ASA00_B5.TIF
                        type: reflective
                        label: Middle Infrared 1
                        number: '5'
                        cell_size: 25.0
                    '6':
                        path: product/LT51140752011016ASA00_B6.TIF
                        type: thermal
                        label: Thermal Infrared
                        number: '6'
                        cell_size: 100.0
                    '7':
                        path: product/LT51140752011016ASA00_B7.TIF
                        type: reflective
                        label: Middle Infrared 2
                        number: '7'
                        cell_size: 25.0
            lineage:
                algorithm:
                    name: LPGS
                    version: 12.7.0
                    parameters: {}
                machine:
                    hostname: r1216
                    runtime_id: cf496d72-1ccb-11e6-b44c-a0000100fe80
                    software_versions:
                        eodatasets:
                            repo_url: https://github.com/GeoscienceAustralia/eo-datasets.git
                            version: '0.4'
                        galpgs:
                            repo_url: https://github.com/GeoscienceAustralia/galpgs.git
                            version: 1.1.1
                        gqa:
                            repo_url: https://github.com/GeoscienceAustralia/gqa.git
                            version: '0.6'
                        pinkmatter: 4.1.4084
                    uname: 'Linux r1216 2.6.32-573.22.1.el6.x86_64 #1 SMP Wed Mar
                        23 03:35:39 UTC 2016 x86_64'
                ancillary_quality: DEFINITIVE
                ancillary:
                    cpf:
                        name: L5CPF20110101_20110331.14
                        uri: /g/data/v10/eoancillarydata/sensor-specific/LANDSAT5/CalibrationParameterFile/L5CPF20110101_20110331.14
                        access_dt: 2016-05-18 19:03:36
                        modification_dt: 2014-11-26 13:03:30
                        checksum_sha1: a5727624151fd2e18e174dc208657a93a7423cb9
                    ephemeris:
                        name: L52011017DEFEPH.S00
                        uri: /g/data/v10/eoancillarydata/sensor-specific/LANDSAT5/DefinitiveEphemeris/LS5_YEAR/2011/L52011017DEFEPH.S00
                        access_dt: 2016-05-18 19:03:36
                        modification_dt: 2011-01-18 09:28:52
                        checksum_sha1: c099fb0c0bc14beced787b20a646b17e4c794d06
                source_datasets:
                    satellite_telemetry_data:
                        id: 092bc1b8-5ffb-11e5-b4fe-ac162d791418
                        ga_label: LS5_TM_STD-RCC_P00_L5TB2011016020017ASA122_0_0_20110116T020017Z20110116T020752
                        ga_level: P00
                        product_type: satellite_telemetry_data
                        creation_dt: 2015-09-21 00:52:29.993507
                        size_bytes: 4826085432
                        checksum_path: package.sha1
                        platform:
                            code: LANDSAT_5
                        instrument:
                            name: TM
                            operation_mode: BUMPER
                        format:
                            name: RCC
                        usgs:
                            interval_id: L5TB2011016020017ASA122
                        acquisition:
                            aos: 2011-01-16 02:00:17
                            los: 2011-01-16 02:07:52
                            groundstation:
                                code: ASA
                                label: Alice Springs
                                eods_domain_code: '002'
                            platform_orbit: 142951
                        image:
                            bands: {}
                        lineage:
                            machine: {}
                            source_datasets: {}
```

**Comment by simonaoliver** [comment]
Level 1 example:

``` yaml
id: 723e4fe2-1cd7-11e6-b44c-a0000100fe80
ga_label: LS5_TM_OTH_P51_GALPGS01-002_114_075_20110116
product_type: level1
product_level: L1T
creation_dt: 2016-05-18 08:42:44
size_bytes: 172773914
checksum_path: package.sha1
platform:
    code: LANDSAT_5
instrument:
    name: TM
    operation_mode: BUMPER
format:
    name: GeoTIFF
usgs:
    scene_id: LT51140752011016ASA00
acquisition:
    groundstation:
        code: ASA
        label: Alice Springs
        eods_domain_code: '002'
extent:
    coord:
        ul:
            lat: -20.72316
            lon: 114.930237
        ur:
            lat: -20.735474
            lon: 117.217916
        ll:
            lat: -22.607272
            lon: 114.903166
        lr:
            lat: -22.62082
            lon: 117.220769
    from_dt: 2011-01-16 02:04:44
    center_dt: 2011-01-16 02:04:57.817019
    to_dt: 2011-01-16 02:05:11
grid_spatial:
    projection:
        geo_ref_points:
            ul:
                x: 284462.5
                y: 7707112.5
            ur:
                x: 522687.5
                y: 7707112.5
            ll:
                x: 284462.5
                y: 7498437.5
            lr:
                x: 522687.5
                y: 7498437.5
        datum: GDA94
        ellipsoid: GRS80
        map_projection: UTM
        orientation: NORTH_UP
        resampling_option: CUBIC_CONVOLUTION
        zone: -50
gqa:
    cep90: 0.75
    colors:
        blue: 192.0
        green: 4033.0
        red: 102.0
        teal: 636.0
        yellow: 97.0
    final_gcp_count: 5000
    ref_date: 2014-06-01
    ref_source: GQA_v2
    ref_source_path: /g/data/v10/eoancillarydata/GCP/GQA_v2/wrs2/114/075/LC81140752014152LGN00_B6.TIF
    residual:
        abs:
            x: 0.34
            y: 0.47
        abs_iterative_mean:
            x: 0.24
            y: 0.32
        iterative_mean:
            x: 0.01
            y: 0.04
        iterative_stddev:
            x: 0.53
            y: 0.73
        mean:
            x: 0.01
            y: -0.0
        stddev:
            x: 1.59
            y: 5.29
browse:
    full:
        path: browse.fr.jpg
        file_type: image/jpg
        cell_size: 25.0
        shape:
            x: 9530
            y: 8348
        red_band: '7'
        green_band: '4'
        blue_band: '1'
    medium:
        path: browse.jpg
        file_type: image/jpg
        cell_size: 232.666015625
        shape:
            x: 1024
            y: 897
        red_band: '7'
        green_band: '4'
        blue_band: '1'
image:
    satellite_ref_point_start:
        x: 114
        y: 75
    cloud_cover_percentage: 43.0
    sun_azimuth: 95.46312368
    sun_elevation: 57.39407158
    sun_earth_distance: 0.9836756
    ground_control_points_model: 47
    geometric_rmse_model: 5.421
    geometric_rmse_model_x: 3.982
    geometric_rmse_model_y: 3.678
    bands:
        '1':
            path: product/LT51140752011016ASA00_B1.TIF
            type: reflective
            label: Visible Blue
            number: '1'
            cell_size: 25.0
        '2':
            path: product/LT51140752011016ASA00_B2.TIF
            type: reflective
            label: Visible Green
            number: '2'
            cell_size: 25.0
        '3':
            path: product/LT51140752011016ASA00_B3.TIF
            type: reflective
            label: Visible Red
            number: '3'
            cell_size: 25.0
        '4':
            path: product/LT51140752011016ASA00_B4.TIF
            type: reflective
            label: Near Infrared
            number: '4'
            cell_size: 25.0
        '5':
            path: product/LT51140752011016ASA00_B5.TIF
            type: reflective
            label: Middle Infrared 1
            number: '5'
            cell_size: 25.0
        '6':
            path: product/LT51140752011016ASA00_B6.TIF
            type: thermal
            label: Thermal Infrared
            number: '6'
            cell_size: 100.0
        '7':
            path: product/LT51140752011016ASA00_B7.TIF
            type: reflective
            label: Middle Infrared 2
            number: '7'
            cell_size: 25.0
lineage:
    algorithm:
        name: LPGS
        version: 12.7.0
        parameters: {}
    machine:
        hostname: r1216
        runtime_id: cf496d72-1ccb-11e6-b44c-a0000100fe80
        software_versions:
            eodatasets:
                repo_url: https://github.com/GeoscienceAustralia/eo-datasets.git
                version: '0.4'
            galpgs:
                repo_url: https://github.com/GeoscienceAustralia/galpgs.git
                version: 1.1.1
            gqa:
                repo_url: https://github.com/GeoscienceAustralia/gqa.git
                version: '0.6'
            pinkmatter: 4.1.4084
        uname: 'Linux r1216 2.6.32-573.22.1.el6.x86_64 #1 SMP Wed Mar 23 03:35:39
            UTC 2016 x86_64'
    ancillary_quality: DEFINITIVE
    ancillary:
        cpf:
            name: L5CPF20110101_20110331.14
            uri: /g/data/v10/eoancillarydata/sensor-specific/LANDSAT5/CalibrationParameterFile/L5CPF20110101_20110331.14
            access_dt: 2016-05-18 19:03:36
            modification_dt: 2014-11-26 13:03:30
            checksum_sha1: a5727624151fd2e18e174dc208657a93a7423cb9
        ephemeris:
            name: L52011017DEFEPH.S00
            uri: /g/data/v10/eoancillarydata/sensor-specific/LANDSAT5/DefinitiveEphemeris/LS5_YEAR/2011/L52011017DEFEPH.S00
            access_dt: 2016-05-18 19:03:36
            modification_dt: 2011-01-18 09:28:52
            checksum_sha1: c099fb0c0bc14beced787b20a646b17e4c794d06
    source_datasets:
        satellite_telemetry_data:
            id: 092bc1b8-5ffb-11e5-b4fe-ac162d791418
            ga_label: LS5_TM_STD-RCC_P00_L5TB2011016020017ASA122_0_0_20110116T020017Z20110116T020752
            ga_level: P00
            product_type: satellite_telemetry_data
            creation_dt: 2015-09-21 00:52:29.993507
            size_bytes: 4826085432
            checksum_path: package.sha1
            platform:
                code: LANDSAT_5
            instrument:
                name: TM
                operation_mode: BUMPER
            format:
                name: RCC
            usgs:
                interval_id: L5TB2011016020017ASA122
            acquisition:
                aos: 2011-01-16 02:00:17
                los: 2011-01-16 02:07:52
                groundstation:
                    code: ASA
                    label: Alice Springs
                    eods_domain_code: '002'
                platform_orbit: 142951
            image:
                bands: {}
            lineage:
                machine: {}
                source_datasets: {}
```
