### ISSUE TITLE
Indexing multilayer HDF files

### ISSUE THREAD

**Issue by giorgiobasile** [opendatacube/eo-datasets#221]
I'm trying to index some MODIS HDF files, my understanding looking at some examples (i.e. [this one](https://datacube-core.readthedocs.io/en/stable/ops/dataset_documents.html#eo3-format)) is that I should produce datasets documents having something like:

```yaml

measurements:
  lc_type_1: 
    path: file.hdf
    layer: LC-Type1 # name of the HDF layer
  lc_type_2:
    path: file.hdf # same file as above
    layer: LC-Type2

``` 

Unfortunately, I don't understand how to achieve this with `eo-datasets`, as the [`note_measurement`](https://eodatasets.readthedocs.io/en/latest/#eodatasets3.DatasetPrepare.note_measurement) and [`write_measurement`](https://eodatasets.readthedocs.io/en/latest/#eodatasets3.DatasetPrepare.note_measurement) APIs do not allow to specify anything like a `layer`.
Is there any solution for this?
